var columns = { // 0 indexed  
  price_status: 0,
  post_status: 1,
  refresh_time: 2,
  car_vin: 3,
  requested_url: 4,
  car_name: 5, 
  car_url: 6, 
  car_price: 7, 
  car_info: 8, 
  car_info2: 9, 
  car_stock: 10, 
  car_odometer: 11, 
  car_fuel_economy: 12, 
  car_exterior_color: 13, 
  car_interior_color: 14, 
  car_special: 15, 
  car_transmission: 16, 
  car_drivetrain: 17, 
  car_engine: 18, 
  car_highlighted_features_1_feature: 19, 
  car_highlighted_features_2_feature: 20, 
  car_highlighted_features_3_feature: 21, 
  car_highlighted_features_4_feature: 22, 
  car_highlighted_features_5_feature: 23, 
  car_highlighted_features_6_feature: 24, 
  car_highlighted_features_7_feature: 25, 
  car_highlighted_features_8_feature: 26, 
  car_package_options_1_name: 27, 
  car_package_options_1_price: 28, 
  car_package_options_1_attribute_1: 29, 
  car_package_options_1_attribute_2: 30, 
  car_package_options_1_attribute_3: 31, 
  car_package_options_1_attribute_10: 32, 
  car_package_options_1_attribute_11: 33, 
  car_package_options_1_attribute_12: 34, 
  car_package_options_2_name: 35, 
  car_package_options_2_price: 36, 
  car_package_options_2_attribute_1: 37, 
  car_package_options_2_attribute_2: 38, 
  car_package_options_2_attribute_3: 39, 
  car_package_options_2_attribute_10: 40, 
  car_package_options_2_attribute_11: 41, 
  car_package_options_2_attribute_12: 42, 
  car_package_options_3_name: 43, 
  car_package_options_3_price: 44, 
  car_package_options_3_attribute_1: 45, 
  car_package_options_3_attribute_2: 46, 
  car_package_options_3_attribute_3: 47, 
  car_package_options_3_attribute_10: 48, 
  car_package_options_3_attribute_11: 49, 
  car_package_options_3_attribute_12: 50, 
  car_package_options_4_name: 51, 
  car_package_options_4_price: 52, 
  car_package_options_4_attribute_1: 53, 
  car_package_options_4_attribute_2: 54, 
  car_package_options_4_attribute_3: 55, 
  car_package_options_4_attribute_10: 56, 
  car_package_options_4_attribute_11: 57, 
  car_package_options_4_attribute_12: 58, 
  car_package_options_5_name: 59, 
  car_package_options_5_price: 60, 
  car_package_options_5_attribute_1: 61, 
  car_package_options_5_attribute_2: 62, 
  car_package_options_5_attribute_3: 63, 
  car_package_options_5_attribute_10: 64, 
  car_package_options_5_attribute_11: 65, 
  car_package_options_5_attribute_12: 66, 
  car_package_options_6_name: 67, 
  car_package_options_6_price: 68, 
  car_package_options_6_attribute_1: 69, 
  car_package_options_6_attribute_2: 70, 
  car_package_options_6_attribute_3: 71, 
  car_special2: 72, 
  car_special3: 73, 
  dealership: 74, 
  vehicle_status: 75, 
  image_source_1: 76, 
}

var formData = {
  'name': data[i][columns.desc],
  'location': data[i][columns.loc],
  'date_start': date_start,
  'date_end': date_end,
  'status': data[i][columns.status],
  'owner': data[i][columns.owner],
  'url': data[i][columns.url],
  'type': data[i][columns.type],
  'event_id': data[i][columns.event_id],
  'price_status' : data[i][columns.price_status],
  'post_status' : data[i][columns.post_status],
  'refresh_time' : data[i][columns.refresh_time],
  'car_vin' : data[i][columns.car_vin],
  'requested_url' : data[i][columns.requested_url],
  'car_name' : data[i][columns.car_name],
  'car_url' : data[i][columns.car_url],
  'car_price' : data[i][columns.car_price],
  'car_info' : data[i][columns.car_info],
  'car_info2' : data[i][columns.car_info2],
  'car_stock' : data[i][columns.car_stock],
  'car_odometer' : data[i][columns.car_odometer],
  'car_fuel_economy' : data[i][columns.car_fuel_economy],
  'car_exterior_color' : data[i][columns.car_exterior_color],
  'car_interior_color' : data[i][columns.car_interior_color],
  'car_special' : data[i][columns.car_special],
  'car_transmission' : data[i][columns.car_transmission],
  'car_drivetrain' : data[i][columns.car_drivetrain],
  'car_engine' : data[i][columns.car_engine],
  'car_highlighted_features_1_feature' : data[i][columns.car_highlighted_features_1_feature],
  'car_highlighted_features_2_feature' : data[i][columns.car_highlighted_features_2_feature],
  'car_highlighted_features_3_feature' : data[i][columns.car_highlighted_features_3_feature],
  'car_highlighted_features_4_feature' : data[i][columns.car_highlighted_features_4_feature],
  'car_highlighted_features_5_feature' : data[i][columns.car_highlighted_features_5_feature],
  'car_highlighted_features_6_feature' : data[i][columns.car_highlighted_features_6_feature],
  'car_highlighted_features_7_feature' : data[i][columns.car_highlighted_features_7_feature],
  'car_highlighted_features_8_feature' : data[i][columns.car_highlighted_features_8_feature],
  'car_package_options_1_name' : data[i][columns.car_package_options_1_name],
  'car_package_options_1_price' : data[i][columns.car_package_options_1_price],
  'car_package_options_1_attribute_1' : data[i][columns.car_package_options_1_attribute_1],
  'car_package_options_1_attribute_2' : data[i][columns.car_package_options_1_attribute_2],
  'car_package_options_1_attribute_3' : data[i][columns.car_package_options_1_attribute_3],
  'car_package_options_1_attribute_10' : data[i][columns.car_package_options_1_attribute_10],
  'car_package_options_1_attribute_11' : data[i][columns.car_package_options_1_attribute_11],
  'car_package_options_1_attribute_12' : data[i][columns.car_package_options_1_attribute_12],
  'car_package_options_2_name' : data[i][columns.car_package_options_2_name],
  'car_package_options_2_price' : data[i][columns.car_package_options_2_price],
  'car_package_options_2_attribute_1' : data[i][columns.car_package_options_2_attribute_1],
  'car_package_options_2_attribute_2' : data[i][columns.car_package_options_2_attribute_2],
  'car_package_options_2_attribute_3' : data[i][columns.car_package_options_2_attribute_3],
  'car_package_options_2_attribute_10' : data[i][columns.car_package_options_2_attribute_10],
  'car_package_options_2_attribute_11' : data[i][columns.car_package_options_2_attribute_11],
  'car_package_options_2_attribute_12' : data[i][columns.car_package_options_2_attribute_12],
  'car_package_options_3_name' : data[i][columns.car_package_options_3_name],
  'car_package_options_3_price' : data[i][columns.car_package_options_3_price],
  'car_package_options_3_attribute_1' : data[i][columns.car_package_options_3_attribute_1],
  'car_package_options_3_attribute_2' : data[i][columns.car_package_options_3_attribute_2],
  'car_package_options_3_attribute_3' : data[i][columns.car_package_options_3_attribute_3],
  'car_package_options_3_attribute_10' : data[i][columns.car_package_options_3_attribute_10],
  'car_package_options_3_attribute_11' : data[i][columns.car_package_options_3_attribute_11],
  'car_package_options_3_attribute_12' : data[i][columns.car_package_options_3_attribute_12],
  'car_package_options_4_name' : data[i][columns.car_package_options_4_name],
  'car_package_options_4_price' : data[i][columns.car_package_options_4_price],
  'car_package_options_4_attribute_1' : data[i][columns.car_package_options_4_attribute_1],
  'car_package_options_4_attribute_2' : data[i][columns.car_package_options_4_attribute_2],
  'car_package_options_4_attribute_3' : data[i][columns.car_package_options_4_attribute_3],
  'car_package_options_4_attribute_10' : data[i][columns.car_package_options_4_attribute_10],
  'car_package_options_4_attribute_11' : data[i][columns.car_package_options_4_attribute_11],
  'car_package_options_4_attribute_12' : data[i][columns.car_package_options_4_attribute_12],
  'car_package_options_5_name' : data[i][columns.car_package_options_5_name],
  'car_package_options_5_price' : data[i][columns.car_package_options_5_price],
  'car_package_options_5_attribute_1' : data[i][columns.car_package_options_5_attribute_1],
  'car_package_options_5_attribute_2' : data[i][columns.car_package_options_5_attribute_2],
  'car_package_options_5_attribute_3' : data[i][columns.car_package_options_5_attribute_3],
  'car_package_options_5_attribute_10' : data[i][columns.car_package_options_5_attribute_10],
  'car_package_options_5_attribute_11' : data[i][columns.car_package_options_5_attribute_11],
  'car_package_options_5_attribute_12' : data[i][columns.car_package_options_5_attribute_12],
  'car_package_options_6_name' : data[i][columns.car_package_options_6_name],
  'car_package_options_6_price' : data[i][columns.car_package_options_6_price],
  'car_package_options_6_attribute_1' : data[i][columns.car_package_options_6_attribute_1],
  'car_package_options_6_attribute_2' : data[i][columns.car_package_options_6_attribute_2],
  'car_package_options_6_attribute_3' : data[i][columns.car_package_options_6_attribute_3],
  'car_special2': data[i][columns.car_special2],
  'car_special3': data[i][columns.car_special3],
  'dealership': data[i][columns.dealership],
  'vehicle_status': data[i][columns.vehicle_status],
  'image_source_1': data[i][columns.image_source_1],
};
